{% set name = "python-memcached" %}
{% set version = "1.61" %}
{% set bundle = "tar.gz" %}
{% set hash_val = "d4bf7aa991f3a131c781ce5a44cd97c1101d0947a1cf32aaaa0915d047bc0a74" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash_val }}

build:
  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record=record.txt
  noarch: python

requirements:
  host:
    - python
    - setuptools

  run:
    - python
    - six >=1.4.0

test:
  imports:
    - memcache

about:
  home: http://www.tummy.com/Community/software/python-memcached/
  license_file: {{ RECIPE_DIR }}/PSF.LICENSE
  license: PSF 2.0
  license_family: PSF
  summary: Pure python memcached client
  dev_url: https://github.com/linsomniac/python-memcached

extra:
  recipe-maintainers:
    - pmlandwehr
