{% set name = "python-memcached" %}
{% set version = "1.62" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/python-memcached-{{ version }}.tar.gz
  sha256: 0285470599b7f593fbf3bec084daa1f483221e68c1db2cf1d846a9f7c2655103

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7

test:
  imports:
    - memcache
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://www.tummy.com/Community/software/python-memcached/
  license_file: PSF.LICENSE
  license: PSF-2.0
  license_family: PSF
  summary: Pure python memcached client
  dev_url: https://github.com/linsomniac/python-memcached

extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpaf
